baseURL = "https://harrymkt.github.io/hguinav"
title = "UI Navigation"
cleanDestinationDir = true
publishDir = "HTML"
enableGitInfo = true
themesDir = "../../"
theme = "hguinav"
[languages]
	[languages.en]
		languageName = "English"
	[languages.my]
		languageName = "Myanmar"

[taxonomies]
	category = "categories"
	tag = "tags"
	author = "authors"

[menus]
	[[menus.main]]
		name = "Home"
		pageRef = "/"
		identifier = "menu_main_home"
		weight = 10
	[[menus.main]]
		name = "Posts"
		pageRef = "/blog"
		identifier = "menu_main_blog"
		weight = 20
	[[menus.main]]
		name = "Documentation"
		pageRef = "/docs"
		identifier = "menu_main_doc"
		weight = 30
	[[menus.main]]
		name = "Authors"
		pageRef = "/authors"
		identifier = "menu_main_author"
		weight = 40

[params]
	display_site_lastmod = true